### ISSUE TITLE
Image modification in latte

### ISSUE THREAD

**Issue by PavelJurasek** [WebChemistry/images#28]
Hi,
I was unable to find a way to modify image in-place in latte template.
In 2.x I was able to write ```{img $path, '200x', 'exact'}```. Is there a way to do the same in 3.x?

**Comment by MartkCz** [comment]
neon:
```yaml
local:
  aliases:
    exact200: 'resite:200,null,exact'
```

`{img $path, exact200}`
