### ISSUE TITLE
Keep image quality

### ISSUE THREAD

**Issue by wohral** [WebChemistry/images#8]
Is there any way, to keep image quality and ignore Image compression?

**Comment by MartkCz** [comment]
only locally.

Uploading: ([more here](https://github.com/WebChemistry/Images/blob/master/src/AbstractStorage.php#L88-L93))

``` php
$image = $this->imageStorage->createImage();
$image->setQuality(100);
// ...
$image->saveUpload(new Nette\Http\FileUpload);
```

Link:

``` php
$image->get('namespace/image.jpg')->setQuality(100)->getLink();
```

In future I probably prepare feature, which allow sets different options for namespace.

``` yaml
namespace:
  quality: 100
  allow:
    - 250x100
    - 300x50
  callback:
  ## ...
```
